---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: keycloak
  labels:
    app: keycloak
data:
  inference-gateway-realm.json: |
    {
      "realm": "inference-gateway-realm",
      "enabled": true,
      "clients": [
        {
          "clientId": "inference-gateway-client",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "your-client-secret",
          "redirectUris": ["*"],
          "webOrigins": ["*"]
        }
      ],
      "users": [
        {
          "username": "admin",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "admin",
              "temporary": false
            }
          ]
        }
      ]
    }
