services:
  inference-gateway:
    image: ghcr.io/inference-gateway/inference-gateway:latest
    pull_policy: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - helloworld-agent
      - calculator-agent
      - weather-agent
      - google-calendar-agent
    networks:
      - a2a-network

  helloworld-agent:
    build:
      context: ./helloworld-agent
      dockerfile: Dockerfile
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - a2a-network

  calculator-agent:
    build:
      context: ./calculator-agent
      dockerfile: Dockerfile
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8082/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - a2a-network

  weather-agent:
    build:
      context: ./weather-agent
      dockerfile: Dockerfile
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8083/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - a2a-network

  google-calendar-agent:
    image: ghcr.io/inference-gateway/google-calendar-agent:latest
    pull_policy: always
    env_file:
      - .env.google
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8084/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - a2a-network

networks:
  a2a-network:
